### ISSUE TITLE
"Crafting system" wiki page is outdated

### ISSUE THREAD

**Issue by ghost** [MovingBlocks/TeraMisc#39]
Hello! I have no thoughts how to craft items in Terasology, because https://github.com/MovingBlocks/Terasology/wiki/Crafting-System page is really out of date. Just nothing happens when I follow instructions provided there. Thanks for attention.

UPD: I found that I can open crafting window by pressing "G" button, but a novice looking for "How to craft in Terasology" goes first to this wiki page, because there are just no more useful links.

**Comment by Cervator** [comment]
Thanks - I've updated the disclaimer on the page about this being a legacy crafting system.

I hope we can make that system work again one day. The wiki and doc in general will always need more updates than we can easily get to :( But it helps with reminders

**Comment by Cervator** [comment]
Page deleted / moved to the Crafting module (which has the old code but hasn't been fixed so far) - https://github.com/Terasology/Crafting

Hopefully it'll work again one day but at least now the confusion should be less :-)
