### ISSUE TITLE
Minor Issue with Translation Guide in Wiki

### ISSUE THREAD

**Issue by rileyschnee** [MovingBlocks/TeraMisc#47]
Under Manual Translation in the Wiki, the path to the flag images is slightly wrong. 
It should be 
`engine/src/main/resources/assets/textures/ui/icons` (texture**s**) 
not 
`engine/src/main/resources/assets/texture/ui/icons`

**Comment by Cervator** [comment]
Thanks! Added the missing `s` real quick :-)
